# Controlled vocabulary for ETDMS degree levels
# Used for Degree Level field on ETD work type
# Term IDs are used as strings. Wrap in quotes to prevent being stored as integers. 
# Term 0 / Undergraduate is not used at CU Library. 
terms:
  - id: "1"
    term: Masters
  - id: "2"
    term: Doctoral
