# Configure repository features 
# See hyrax/config/features.rb for default settings

# Until self-deposit is supported, allow passive acceptance of
# agreement by repository admins on behalf of faculty depositors
#
# ... except until Hyrax issue 6517 is fixed, set active acceptance = true
# See https://github.com/samvera/hyrax/issues/6517
active_deposit_agreement_acceptance:
  enabled: true

# Do not show any information about private files on public works
hide_private_items:
  enabled: true
